#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d pianissimo piano forte fortissimo

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a kitty state=floating follow=on
bspc rule -a firefox-esr desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#bspwm autostart
pkill sxhkd
pkill polybar
sxhkd &
polybar top &
